linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/spf13/viper

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - dogsled
        - dupl
        - exhaustive
        - exportloopref
        - goconst
        - gofmt
        - goimports
        - golint
        - goprintffuncname
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - prealloc
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace

        # fixme
        # - errcheck
        # - gci
        # - gochecknoglobals
        # - gochecknoinits
        # - gocognit
        # - gocritic
        # - gocyclo
        # - godot
        # - gofumpt
        # - gosec
        # - gosimple
        # - lll
        # - nlreturn
        # - scopelint

        # unused
        # - depguard
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - testpackage
        # - wsl
